import { Product } from './types';

export const CATEGORIES = ['Supplements', 'Skincare', 'Hair Care', 'Teas', 'Oils'];
export const DOSHAS = ['Vata', 'Pitta', 'Kapha', 'Tridoshic'];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Organic Ashwagandha Root',
    description: 'Ancient adaptogen to help your body manage stress and boost energy levels naturally.',
    price: 24.99,
    category: 'Supplements',
    dosha: 'Vata',
    image: 'https://picsum.photos/400/400?random=1',
    rating: 4.8,
    reviews: 124,
    benefits: ['Stress Relief', 'Energy Boost', 'Sleep Support'],
    ingredients: ['Organic Ashwagandha Root Extract', 'Black Pepper Extract'],
    inStock: true,
  },
  {
    id: '2',
    name: 'Triphala Digestive Balance',
    description: 'A traditional blend of three fruits to support healthy digestion and detoxification.',
    price: 19.50,
    category: 'Supplements',
    dosha: 'Tridoshic',
    image: 'https://picsum.photos/400/400?random=2',
    rating: 4.6,
    reviews: 89,
    benefits: ['Digestion', 'Detox', 'Nutrient Absorption'],
    ingredients: ['Amla', 'Bibhitaki', 'Haritaki'],
    inStock: true,
  },
  {
    id: '3',
    name: 'Kumkumadi Miraculous Face Oil',
    description: 'A luxurious blend of saffron and herbs to brighten complexion and reduce signs of aging.',
    price: 45.00,
    category: 'Skincare',
    dosha: 'Pitta',
    image: 'https://picsum.photos/400/400?random=3',
    rating: 4.9,
    reviews: 210,
    benefits: ['Radiance', 'Anti-aging', 'Hydration'],
    ingredients: ['Saffron', 'Sandalwood', 'Manjistha'],
    inStock: true,
  },
  {
    id: '4',
    name: 'Brahmi Focus Tea',
    description: 'Enhance cognitive function and mental clarity with this soothing herbal tea blend.',
    price: 15.99,
    category: 'Teas',
    dosha: 'Tridoshic',
    image: 'https://picsum.photos/400/400?random=4',
    rating: 4.5,
    reviews: 56,
    benefits: ['Focus', 'Memory', 'Calmness'],
    ingredients: ['Brahmi Leaves', 'Gotu Kola', 'Cardamom'],
    inStock: true,
  },
  {
    id: '5',
    name: 'Bhringraj Hair Vitality Oil',
    description: 'Intensive hair treatment to prevent hair fall and promote lush, thick growth.',
    price: 28.00,
    category: 'Hair Care',
    dosha: 'Pitta',
    image: 'https://picsum.photos/400/400?random=5',
    rating: 4.7,
    reviews: 140,
    benefits: ['Hair Growth', 'Scalp Health', 'Prevents Greying'],
    ingredients: ['Bhringraj', 'Amla', 'Coconut Oil'],
    inStock: true,
  },
  {
    id: '6',
    name: 'Kapha Balancing Massage Oil',
    description: 'Invigorating warm herbal oil to stimulate circulation and reduce lethargy.',
    price: 22.50,
    category: 'Oils',
    dosha: 'Kapha',
    image: 'https://picsum.photos/400/400?random=6',
    rating: 4.4,
    reviews: 32,
    benefits: ['Circulation', 'Energy', 'Detox'],
    ingredients: ['Mustard Oil', 'Ginger', 'Cinnamon'],
    inStock: true,
  }
];
